spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

logging.level.org.springframework: DEBUG

---
spring:
  profiles: docker
#   zipkin:
#     baseUrl: http://tracing-server:9411
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

opentracing:
  jaeger:
    udp-sender.host: tracing-server
    udp-sender.port: 6831
    log-spans: true
